version: '3.1'

services:

  wordpress:
    image: wordpress:5.8.1
    # restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: wp
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      default:
        aliases:
          - "apirone.loc"
 
  db:
    image: mysql:5.7
    # restart: always
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      #MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_ROOT_PASSWORD: 'toor'
    volumes:
      - ./data/mysql:/var/lib/mysql

volumes:
  wordpress:
  db:
